version: '2'
services:
    testapp-app:
        image: testapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://testapp-postgresql:5432/TestApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testapp-postgresql:
        extends:
            file: postgresql.yml
            service: testapp-postgresql
